server:
  port: 8130 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-oss # 服务名

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 3000ms  #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1 #最大阻塞等待时间。负值表示没有限制，默认-1
        max-idle: 8 #最大空闲连接数，默认8
        min-idle: 0 #最小空闲连接数，默认0

aliyun:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKey: 填自己的key
  accessSecret: 填自己的Secret
  bucketName: lele-file
