server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  redis:
    host: 114.55.233.141
    port: 6379
    database: 0
    password:
    timeout: 3000ms  #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20 #最大连接数，负值表示没有限制，默认8
        max-wait: -1 #最大阻塞等待时间。负值表示没有限制，默认-1
        max-idle: 8 #最大空闲连接数，默认8
        min-idle: 0 #最小空闲连接数，默认0

yuntongxun:
  server-ip: app.cloopen.com
  server-port: 8883
  account-sId: 8aaf07087fe90a32017ff9d144900409
  account-token: c83320522d9a4282a0ec3c217a660306
  app-id: 8aaf07087fe90a32017ff9d145880410
  template-id: 1
